language: node_js
os: linux
dist: xenial
node_js:
  - 14
jobs:
  include:
    - stage: build
      name: "checking style"
      script: npm run linter
    - script: npm ci
      name: "running app build"
    - stage: test
      name: "running app tests"
      script: npm test
    - stage: coverage
      name: "getting code coverage"
      script: npm run coverage && bash <(curl -s https://codecov.io/bash)