# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      mongo:
        image: mongo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Applying npm install
      uses: bahmutov/npm-install@v1
    - run: npm ci

    - name: Checks style through linting
      run: npm run linter

    - name: Runs test ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run coverage
      env:
        PORT: 3020
        NODE_ENV: test
        MONGODB_URI: mongodb://mongo:27017/getir-test
    
    - name: Collects coverage with codecov
      run: npm run codecov

    - uses: codecov/codecov-action@v1
      # with:
      #   token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        # files: ./coverage1.xml,./coverage2.xml # optional
        # flags: unittests # optional
        # name: codecov-umbrella # optional
        # fail_ci_if_error: true # optional (default = false)
        # verbose: false # optional (default = false)
